"""empty message

Revision ID: 267b64a1acc8
Revises: b7559c985e80
Create Date: 2023-01-25 18:50:02.939305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267b64a1acc8'
down_revision = 'b7559c985e80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machine', sa.Column('pm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'virtual_machine', 'physical_machine', ['pm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_machine', type_='foreignkey')
    op.drop_column('virtual_machine', 'pm_id')
    # ### end Alembic commands ###
