"""empty message

Revision ID: 2b033ad352be
Revises: 7933f6394f7f
Create Date: 2023-01-29 16:44:16.132825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b033ad352be'
down_revision = '7933f6394f7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machine', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_machine', 'size')
    # ### end Alembic commands ###
