"""empty message

Revision ID: b6be6832c6e0
Revises: 267b64a1acc8
Create Date: 2023-01-26 22:36:55.298142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6be6832c6e0'
down_revision = '267b64a1acc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('vm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'virtual_machine', ['vm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'vm_id')
    # ### end Alembic commands ###
